language: python
python:
  - "2.7"
  - "3.4"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test --cov chunky

after_success:
    - if [[ $ENV == python=3.4* ]]; then
          COVERALLS_REPO_TOKEN=Ea59494Ak3Gj2GIBhHxt8uKxZUd2ouveS coveralls;
      fi
